#!/usr/bin/env python3
"""Move everything produced while building this into testing-archive/.

    python3 retire_archive.py            # show what would move
    python3 retire_archive.py --yes      # move it

Run ONCE, at the point the system stops being built and starts being used.

`archive/` is meant to be the operating record: a dated snapshot per scan,
accumulating for as long as the fleet runs. What is in it today is not that. It
is two days of development — thirty rebuilds of the same reports in an afternoon,
several of them from code that was wrong at the time and has since been fixed.
Leaving that in place would mean the first year of "history" is mostly noise
about scanners that no longer exist.

So it is preserved, not deleted — it is the record of how the numbers were
arrived at, and some of it documents bugs worth remembering — but it is moved
somewhere that will not be confused for operating history.

    testing-archive/<stamp>/archive/     everything archive/ held
    testing-archive/<stamp>/<machine>/   each computer's documents as they stand
    archive/                             empty, for the real run

BOTH REPOSITORIES

The corpus repo gets the same treatment for the same reason: its per-machine
documents were rewritten repeatedly today as the generator changed.
"""

import argparse
import datetime
import json
import pathlib
import shutil
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import paths


def size_of(p):
    return sum(f.stat().st_size for f in p.rglob("*") if f.is_file()) if p.is_dir() else 0


def retire_stale_machines(root, stamp, dry):
    """Move machine folders scanned by an older version out of the fleet.

    A folder produced by a superseded scanner is not "slightly out of date" —
    it was counted by code with known defects. Four of the bugs fixed today
    changed totals: a reader that missed profiles outside $HOME, a counter
    applied per profile instead of per account, a Claude reader with its own
    narrow glob, and a redactor weaker than its verifier. Leaving those numbers
    in the collective means every total silently mixes accountings.

    So they are moved to the testing archive, not deleted, and the fleet is
    left holding only what the current scanner produced. Each machine restores
    itself the moment it runs `update.py` again — which is the point: the
    number goes back up because it was re-measured, not because it was kept.
    """
    import sys as _s
    _s.path.insert(0, str(root))
    import sessions, json
    cur = sessions.scanner_version()
    dest = root / "testing-archive" / stamp / "stale-machines"
    moved = []
    for d in paths.machine_folders(root):
        tj = paths.find(d, "totals.json")
        if not tj:
            continue
        try:
            v = json.loads(tj.read_text(encoding="utf-8")).get("scanner_version")
        except Exception:
            v = None
        if v == cur:
            continue
        moved.append((d.name, v or "pre-versioning"))
        if not dry:
            dest.mkdir(parents=True, exist_ok=True)
            shutil.move(str(d), str(dest / d.name))
            # THE LEDGER IS NOT A DERIVED DOCUMENT AND MUST NOT BE RETIRED.
            #
            # Everything else in a machine folder can be regenerated by
            # re-running the scanner. token_ledger.jsonl cannot: it is the
            # append-only record of sessions whose transcripts may no longer
            # exist, and re-scanning produces rows only for what is still on
            # disk. Moving it aside and letting `update` create a fresh one
            # resets the lifetime total to whatever survives today — which is
            # the exact loss the ledger was written to prevent, performed by
            # this repository's own housekeeping command.
            #
            # Caught on the first real run: it moved 269 rows / 8,415,422,675
            # tokens into testing-archive, and the next scan would have started
            # from zero without a word.
            led = dest / d.name / paths.MACHINE / "token_ledger.jsonl"
            if led.is_file():
                keep = d / paths.MACHINE
                keep.mkdir(parents=True, exist_ok=True)
                shutil.copy2(str(led), str(keep / "token_ledger.jsonl"))
                print(f"     {d.name:32} ledger kept in place "
                      f"({sum(1 for _ in led.open()):,} rows)")
            # .machine-id is IDENTITY, not a derived document either. Retiring
            # it makes the computer forget which folder is its own, and the very
            # next `run.py update` stops with "Cannot tell which folder belongs
            # to this computer" — which is what happened on the first real run.
            # It fails loudly rather than guessing, which is right, but there is
            # no reason to create the failure: the folder is not in the fleet
            # while it holds no totals.json, so keeping the marker costs nothing
            # and saves every machine a --machine --label round trip after every
            # clean.
            mid = dest / d.name / ".machine-id"
            if mid.is_file():
                shutil.copy2(str(mid), str(d / ".machine-id"))
    print(f"\n  machines on an older scanner ({'would move' if dry else 'moved'}):")
    for name, v in moved:
        print(f"     {name:32} {v}")
    if not moved:
        print("     none — every machine is on the current scanner")
    return moved


def retire(root, stamp, dry, label):
    from update import stamp_path
    dest = root / "testing-archive" / stamp_path(stamp)
    moved = []

    arc = root / "archive"
    if arc.is_dir() and any(arc.iterdir()):
        moved.append(("archive/", size_of(arc), len(list(arc.rglob("*")))))
        if not dry:
            dest.mkdir(parents=True, exist_ok=True)
            shutil.move(str(arc), str(dest / "archive"))
            arc.mkdir(exist_ok=True)
            (arc / ".gitkeep").write_text("")

    # A copy of every computer's documents as they stand right now, so the
    # testing archive is a complete picture of the moment rather than only the
    # snapshots that happened to be taken.
    for mdir in sorted(d for d in root.iterdir() if d.is_dir()):
        if mdir.name in ("archive", "testing-archive", "corpus", "merged",
                         "digests", "dist", "docker", ".git", "__pycache__"):
            continue
        for sub in (paths.HUMAN, paths.MACHINE):
            src = mdir / sub
            if not src.is_dir():
                continue
            moved.append((f"{mdir.name}/{sub}/", size_of(src),
                          len(list(src.rglob("*")))))
            if not dry:
                out = dest / mdir.name / sub
                out.parent.mkdir(parents=True, exist_ok=True)
                shutil.copytree(src, out, dirs_exist_ok=True)

    for sub in (paths.HUMAN, paths.MACHINE):
        src = root / sub
        if src.is_dir():
            moved.append((f"{sub}/ (collective)", size_of(src),
                          len(list(src.rglob("*")))))
            if not dry:
                shutil.copytree(src, dest / "collective" / sub, dirs_exist_ok=True)

    total = sum(m[1] for m in moved)
    print(f"  {label}")
    for name, sz, n in moved:
        print(f"     {name:42} {n:>5} files  {sz/1e6:>8.1f} MB")
    print(f"     {'':42} {'':>5}         {total/1e6:>8.1f} MB total")
    if not dry and moved:
        (dest / "WHY.md").write_text(
            f"# Testing archive — {stamp}\n\n"
            "Everything produced while this system was being built, moved here "
            "so that `archive/` could start clean for real operation.\n\n"
            "It is kept rather than deleted: it records how the numbers were "
            "arrived at, including several that were wrong at the time. But it "
            "is not operating history — it is thirty rebuilds of the same "
            "reports in an afternoon, some of them from scanners that have "
            "since been replaced.\n\n"
            "Nothing here should be read as usage over time.\n",
            encoding="utf-8")
    return moved, dest



def _inventory(d):
    """{relative path: size} for every file under d. The comparison unit."""
    return {str(f.relative_to(d)): f.stat().st_size
            for f in d.rglob("*") if f.is_file()}


def verify_and_wipe(root, dest, label, dry):
    """Remove each computer's folder — but ONLY where its copy is verified.

    `retire` COPIES the machine folders into testing-archive/. Copying and then
    deleting are two steps, and a wipe that assumes the first one worked is how
    a fleet loses the only record of a scan. So every file is compared by
    relative path AND size against what landed in this repo's OWN testing
    archive, per repo, and a folder whose copy does not match is REFUSED and
    left exactly where it is. A refusal is not a failure of the run; it is the
    check doing its job on the one folder that would have been lost.
    """
    wiped, refused = [], []
    skip = {"archive", "testing-archive", "corpus", "merged", "digests",
            "dist", "docker", ".git", "__pycache__"}
    for mdir in sorted(d for d in root.iterdir() if d.is_dir()):
        if mdir.name in skip:
            continue
        for sub in (paths.HUMAN, paths.MACHINE):
            src = mdir / sub
            if not src.is_dir():
                continue
            out = dest / mdir.name / sub
            want, got = _inventory(src), (_inventory(out) if out.is_dir() else {})
            missing = {k: v for k, v in want.items() if got.get(k) != v}
            if missing:
                refused.append((f"{mdir.name}/{sub}", len(missing), len(want)))
                continue
            wiped.append((f"{mdir.name}/{sub}", len(want)))
            if not dry:
                shutil.rmtree(src)
    print(f"\n  {label} — wipe after verify")
    for name, n in wiped:
        print(f"     {'WIPED' if not dry else 'would wipe':12} {name:38} {n:>5} file(s) verified in testing-archive")
    for name, m, n in refused:
        print(f"     {'REFUSED':12} {name:38} {m} of {n} file(s) did not match — left in place")
    if not wiped and not refused:
        print("     nothing to wipe")
    return wiped, refused


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--yes", action="store_true")
    ap.add_argument("--wipe", action="store_true",
                    help="after the copy is VERIFIED, remove each computer's "
                         "folder from every repo")
    ap.add_argument("--corpus", default=str(pathlib.Path.home() / "deadreckon-record"))
    args = ap.parse_args()
    dry = not args.yes
    root = pathlib.Path(__file__).parent
    stamp = datetime.datetime.now().astimezone().strftime("%Y-%m-%dT%H-%M-%S")

    print(f"{'DRY RUN — nothing moved' if dry else 'RETIRING'}   {stamp}\n")
    _, dest_count = retire(root, stamp, dry, "deadreckon-count")
    retire_stale_machines(root, stamp, dry)
    if args.wipe:
        verify_and_wipe(root, dest_count, "deadreckon-count", dry)
    corpus = pathlib.Path(args.corpus)
    if corpus.is_dir():
        print()
        _, dest_rec = retire(corpus, stamp, dry, "deadreckon-record")
        if args.wipe:
            verify_and_wipe(corpus, dest_rec, "deadreckon-record", dry)

    print(f"\n  archive/ is {'still full' if dry else 'now empty and ready for the real run'}")
    if dry:
        print("  re-run with --yes to move.")


if __name__ == "__main__":
    main()
