#!/usr/bin/env python3
"""Ask questions of the session records: longest, heaviest, streaks, totals.

Reads every `<machine>/sessions.json` written by sessions.py and answers across
any slice of them. Filter by machine, by CLI, by provider, or take the lot.

    python3 stats.py                                  everything
    python3 stats.py --machine hp-laptop-linux
    python3 stats.py --cli claude --top 10
    python3 stats.py --cli copilot --by tokens
    python3 stats.py --provider anthropic             every CLI that ran Claude

`--cli` and `--provider` are different questions. `--cli copilot` is "what did
the Copilot subscription cost me", including its Claude usage. `--provider
anthropic` is "how much did Anthropic serve", across Claude Code and Copilot
both. Conflating them is how you double-count or lose a vendor entirely.

Definitions follow Claude Code's own stats cache so the numbers are comparable
to what it reports: longest session is ranked by DURATION (not tokens), and
streaks are computed over the set of distinct active dates.
"""

import argparse
import json
import pathlib
import paths
from collections import Counter, defaultdict
from datetime import date, timedelta


def human(n):
    for unit, size in (("T", 1e12), ("B", 1e9), ("M", 1e6), ("K", 1e3)):
        if n >= size:
            return f"{n / size:.2f}{unit}"
    return str(int(n))


def hm(minutes):
    h, m = divmod(int(round(minutes)), 60)
    return f"{h}h {m:02d}m" if h else f"{m}m"


def load(root, machine):
    out = []
    for _mdir, f in paths.iter_machine_files(root, "sessions.json"):
        if machine not in (None, "all") and f.parent.name != machine:
            continue
        try:
            d = json.loads(f.read_text(encoding="utf-8"))
        except Exception:
            continue
        for s in d.get("sessions", []):
            s["machine"] = d.get("machine", f.parent.name)
            s["folder"] = f.parent.name
            out.append(s)
    return out


def streaks(dates):
    """Current and longest run of consecutive active days.

    Mirrors Claude Code's own zY9(): walk back from today while each date is
    present for the current streak; scan the sorted distinct dates for the
    longest consecutive run.
    """
    if not dates:
        return 0, 0, None, None
    days = sorted({date.fromisoformat(d) for d in dates})
    have = set(days)
    cur, probe = 0, date.today()
    while probe in have:
        cur += 1
        probe -= timedelta(days=1)
    best = run = 1
    b_start = b_end = days[0]
    r_start = days[0]
    for prev, cud in zip(days, days[1:]):
        if (cud - prev).days == 1:
            run += 1
        else:
            run, r_start = 1, cud
        if run > best:
            best, b_start, b_end = run, r_start, cud
    return cur, best, b_start, b_end


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--machine", default="all")
    ap.add_argument("--cli", default="all", help="claude | copilot | codex | all")
    ap.add_argument("--provider", default="all",
                    help="anthropic | openai | deepseek | google | all")
    ap.add_argument("--top", type=int, default=5)
    ap.add_argument("--by", default="duration", choices=("duration", "tokens"))
    ap.add_argument("--root", default=str(pathlib.Path(__file__).parent))
    args = ap.parse_args()

    root = pathlib.Path(args.root)
    S = load(root, args.machine)
    if args.cli != "all":
        S = [s for s in S if s["cli"] == args.cli]
    if args.provider != "all":
        S = [s for s in S if s.get("provider") == args.provider]
    if not S:
        raise SystemExit("no sessions match that slice "
                         "(run sessions.py on this machine first)")

    scope = (f"machine={args.machine}  cli={args.cli}  provider={args.provider}")
    tok = sum(s["total"] for s in S)
    sent = sum(s.get("sent", 0) for s in S)
    recv = sum(s.get("received", 0) for s in S)
    mins = sum(s["duration_min"] for s in S)
    days = [s["start"][:10] for s in S if s.get("start")]
    cur, best, b0, b1 = streaks(days)

    print(f"=== {scope} ===\n")
    print(f"  sessions      {len(S):,}")
    print(f"  time          {hm(mins)}  ({mins/60:,.1f} session-hours, active)")
    print(f"  tokens        {tok:,}  ({human(tok)})")
    print(f"    sent        {sent:,}   input + cache write + cache read")
    print(f"    received    {recv:,}   generated by the model")
    print(f"  turns         {sum(s['turns'] for s in S):,}")
    if days:
        print(f"  active days   {len(set(days))}   {min(days)} .. {max(days)}")
        print(f"  streak        current {cur}, longest {best}"
              + (f" ({b0} .. {b1})" if b0 else ""))

    key = (lambda s: s["duration_min"]) if args.by == "duration" else (lambda s: s["total"])
    print(f"\n  --- top {args.top} sessions by {args.by} ---")
    print(f"  {'when':11s} {'cli':8s} {'dur':>9s} {'tokens':>12s} {'turns':>6s}  project / model")
    for s in sorted(S, key=key, reverse=True)[:args.top]:
        print(f"  {(s.get('start') or '?')[:10]:11s} {s['cli']:8s} "
              f"{hm(s['duration_min']):>9s} {human(s['total']):>12s} {s['turns']:>6,}  "
              f"{(s.get('project') or '-')[:34]} · {s.get('model','?')}")

    per_day = defaultdict(lambda: [0, 0.0])
    for s in S:
        if s.get("start"):
            e = per_day[s["start"][:10]]
            e[0] += s["total"]
            e[1] += s["duration_min"]
    if per_day:
        d_tok = max(per_day.items(), key=lambda kv: kv[1][0])
        d_hrs = max(per_day.items(), key=lambda kv: kv[1][1])
        print(f"\n  busiest day   {d_tok[0]}  {human(d_tok[1][0])} tokens")
        # Session-hours, not wall-clock: parallel agents overlap, so a single
        # day can legitimately exceed 24h of summed session time.
        print(f"  longest day   {d_hrs[0]}  {hm(d_hrs[1][1])} of session-time"
              + ("  (parallel agents overlap)" if d_hrs[1][1] > 1440 else ""))

    hours = Counter()
    for s in S:
        if s.get("start") and len(s["start"]) >= 13:
            try:
                hours[int(s["start"][11:13])] += 1
            except ValueError:
                pass
    if hours:
        peak = hours.most_common(1)[0]
        bars = "".join("▁▂▃▄▅▆▇█"[min(7, int(hours.get(h, 0) / max(hours.values()) * 7))]
                       for h in range(24))
        print(f"\n  when you work {bars}")
        print(f"                00      06      12      18    23   peak {peak[0]:02d}:00")

    for dim in ("machine", "cli", "provider", "account"):
        agg = defaultdict(lambda: [0, 0, 0.0])
        for s in S:
            e = agg[s.get(dim) or "-"]
            e[0] += 1
            e[1] += s["total"]
            e[2] += s["duration_min"]
        if len(agg) > 1:
            print(f"\n  --- by {dim} ---")
            for k, (n, t, m) in sorted(agg.items(), key=lambda kv: -kv[1][1]):
                print(f"  {k[:38]:38s} {n:5d} sess {hm(m):>9s} {human(t):>10s}")

    unc = []
    for _mdir, f in paths.iter_machine_files(root, "sessions.json"):
        try:
            unc += (json.loads(f.read_text(encoding="utf-8")).get("uncountable_tools") or [])
        except Exception:
            pass
    bad = [u for u in unc if not u.get("records_token_usage")]
    if bad and args.cli == "all":
        print("\n  --- installed but not countable ---")
        for u in bad:
            extra = (f", {u['conversation_dbs']} conversation DBs"
                     if u.get("conversation_dbs") else "")
            print(f"  {u['tool']:20s} {u['files']:,} files{extra} — records no token usage")


if __name__ == "__main__":
    main()
